format = "$directory $git_branch$python$time $character"

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"

[directory]
style = "bg:#3d59a1 fg:#c0caf5"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = " "
style = "bg:#7aa2f7 fg:#1a1b26"
format = '[[ $symbol$branch ](bg:#7aa2f7 fg:#1a1b26)]($style)'

[python]
symbol = "🐍 "
style = "bg:#9ece6a fg:#1a1b26"
format = '[[ $symbol$version ](bg:#9ece6a fg:#1a1b26)]($style)'

[time]
disabled = false
style = "bg:#1a1b26 fg:#7aa2f7"
format = '[[  $time ](bg:#1a1b26 fg:#7aa2f7)]($style)'
time_format = "%I:%M %p"
