github.com:
    users:
        Kyler2486:
            oauth_token: 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
    git_protocol: https
    user: Kyler2486
    oauth_token: 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
